<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="thunderdome" name="com.wordpressTest.tests.sanityTests.TestC" tests="2" failures="0" timestamp="28 Jan 2016 14:51:18 GMT" time="5.106" errors="1">
  <testcase name="firstTestCaseB" time="0.103" classname="com.wordpressTest.tests.sanityTests.TestC"/>
  <testcase name="secondTestCaseB" time="5.003" classname="com.wordpressTest.tests.sanityTests.TestC">
    <error type="org.testng.SkipException" message="Skipping this test with exception">
      <![CDATA[org.testng.SkipException: Skipping this test with exception
	at com.wordpressTest.tests.sanityTests.TestC.secondTestCaseB(TestC.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- secondTestCaseB -->
</testsuite> <!-- com.wordpressTest.tests.sanityTests.TestC -->
